// Promise.reject

Promise.reject(1)
.catch(err => {
  console.log(err)
})
